"""Prove the R2 credential split against the live buckets (CK-33).

The media pipeline record (§3, 1.3.0) claims that with two buckets "the
credential the serving path uses cannot read quarantine" — the structural
half of "nothing is ever served from quarantine." Until this script existed
that claim rested on a Cloudflare form having been filled in the way a
planning chat described. A mistyped scope would leave the guarantee
decorative with nothing to notice. This script is the notice.

What it does, in order, through app/services/storage.py (so the client
construction the application uses is what gets tested):

  1. presigns a PUT with the UPLOAD credential and actually uploads a small
     GENERATED test object into quarantine — then sends a body of another
     length to the same URL and expects R2 to refuse it (§6.6: the size is
     signed, not trusted);
  2. reads the object back with the UPLOAD credential — asserted
     POSITIVELY, because R2 has no write-only level (§3's honest bound);
     pinning it makes a future narrowing or widening visible;
  3. tries to read the same object with the SERVE credential and expects
     to be REFUSED — §3's guarantee, and the reason this script exists.
     Refusal is distinguished from every other failure: a network error, a
     wrong endpoint, a missing bucket, or a broken key is a FAIL, never a
     pass. "It didn't work" is not the claim "it was refused";
  4. pins the other two edges of the split — the UPLOAD credential refused
     on published, the SERVE credential refused when WRITING to published;
  5. confirms the SERVE credential can read published (a list, and a
     presigned GET through the serving path);
  6. deletes the test object with the UPLOAD credential in a `finally`, so a
     failure mid-run leaves nothing behind. The bucket's 24-hour lifecycle
     rule is the backstop, not the plan.

The test object is generated bytes under an obvious key and never a real
image. Output is outcomes, counts, and bucket names only — never a
credential, never a presigned URL (a bearer credential carrying the Access
Key ID), never an object's contents; failures print the exception class and
the S3 error code, not the message.

Run it where the credentials already live, so they never leave Render:

    Render dashboard -> covey-keep-api -> Shell
    cd ~/project/src/backend && python scripts/verify_r2_credentials.py

Locally it reads the seven R2_* values from the process environment or
backend/.env (the same two tokens as the dashboard — never a third).

If assertion 3 fails, that is a finding about live infrastructure holding
real buckets, not a script bug. Report it and stop; do not adjust the
assertion to make it pass.

Exit code is 0 only if every assertion passed.
"""

from __future__ import annotations

import os
import sys
import urllib.error
import urllib.request
import uuid
from pathlib import Path
from typing import Callable, Optional

BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_DIR))

from botocore.exceptions import (  # noqa: E402
    BotoCoreError,
    ClientError,
    ConnectionClosedError,
    ConnectTimeoutError,
    EndpointConnectionError,
    ReadTimeoutError,
    SSLError,
)

try:
    # Importing app.config constructs the settings singleton, so the seven
    # R2_* values (and the rest of the env surface) must be present — in the
    # process environment on Render, or backend/.env locally.
    from app.config import settings
    from app.services import storage
except Exception as exc:  # pragma: no cover - operator-facing guidance
    raise SystemExit(
        f"Could not load app.config ({exc.__class__.__name__}). The env surface in "
        "backend/.env.example - the seven R2_* values included - must be present in "
        "the process environment or backend/.env."
    )

# The one operation the whole script turns on is telling "refused" apart from
# everything else. These sets are that classification. A 403 with a code not
# listed here is deliberately "other" (a FAIL): only a code that means "you
# authenticated, and this is not yours to touch" may pass assertion 3.
REFUSAL_CODES = {"AccessDenied", "Forbidden", "AllAccessDisabled"}
# The credential itself was rejected. A serve key with a typo is refused
# everywhere — on quarantine AND on published — and that must not read as a
# correctly narrow scope.
BAD_CREDENTIAL_CODES = {
    "InvalidAccessKeyId",
    "SignatureDoesNotMatch",
    "Unauthorized",
    "InvalidSignature",
    "AuthorizationHeaderMalformed",
    "InvalidToken",
    "ExpiredToken",
}
NOT_FOUND_CODES = {"NoSuchBucket", "NoSuchKey", "NotFound", "404"}
NETWORK_ERRORS = (
    EndpointConnectionError,
    ConnectTimeoutError,
    ReadTimeoutError,
    SSLError,
    ConnectionClosedError,
)

TEST_KEY_PREFIX = "verify-r2-credentials/"
TEST_CONTENT_TYPE = "application/octet-stream"
HTTP_TIMEOUT_SECONDS = 30


class Checks:
    """A pass/fail tally that prints as it goes (verify_schema.py's shape)."""

    def __init__(self) -> None:
        self.passed = 0
        self.failed = 0

    def check(self, ok: bool, label: str, detail: str = "") -> bool:
        if ok:
            self.passed += 1
            print(f"PASS  {label}")
        else:
            self.failed += 1
            print(f"FAIL  {label}" + (f"  --  {detail}" if detail else ""))
        return ok

    def info(self, label: str, value: object) -> None:
        print(f"INFO  {label}: {value}")


def classify(exc: BaseException) -> tuple[str, str]:
    """(kind, detail) for a failed request. kind is one of `refused`,
    `not_found`, `bad_credential`, `network`, `other`. detail names the
    exception class, the S3 error code and the HTTP status — never the
    message, never a URL."""
    if isinstance(exc, ClientError):
        error = exc.response.get("Error", {}) or {}
        code = str(error.get("Code") or "")
        status = (exc.response.get("ResponseMetadata", {}) or {}).get("HTTPStatusCode")
        detail = f"ClientError {code or '<no code>'} (HTTP {status})"
        if code in REFUSAL_CODES:
            return "refused", detail
        if code in BAD_CREDENTIAL_CODES:
            return "bad_credential", detail
        if code in NOT_FOUND_CODES or status == 404:
            return "not_found", detail
        return "other", detail
    if isinstance(exc, NETWORK_ERRORS):
        return "network", exc.__class__.__name__
    if isinstance(exc, BotoCoreError):
        return "other", exc.__class__.__name__
    if isinstance(exc, urllib.error.HTTPError):
        # Only reached for a presigned request; the status is the whole story.
        if exc.code == 403:
            return "refused", f"HTTP {exc.code}"
        if exc.code == 404:
            return "not_found", f"HTTP {exc.code}"
        return "other", f"HTTP {exc.code}"
    if isinstance(exc, (urllib.error.URLError, OSError)):
        reason = getattr(exc, "reason", None)
        return "network", f"{exc.__class__.__name__} ({reason.__class__.__name__})"
    return "other", exc.__class__.__name__


def http_request(method: str, url: str, headers: dict[str, str], body: Optional[bytes]) -> int:
    """Perform one presigned request and return the HTTP status. Any 4xx/5xx
    is returned as the status, not raised; only a transport failure raises.
    urllib sets Content-Length from the body when the caller does not — the
    mismatch probe relies on exactly that."""
    request = urllib.request.Request(url, data=body, method=method, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=HTTP_TIMEOUT_SECONDS) as response:
            return int(response.status)
    except urllib.error.HTTPError as exc:
        return int(exc.code)


HttpFn = Callable[[str, str, dict[str, str], Optional[bytes]], int]


def _fail_detail(kind: str, detail: str) -> str:
    words = {
        "refused": "refused",
        "not_found": "not found - the request reached the store and was not refused",
        "bad_credential": "the credential itself was rejected",
        "network": "network - the request never got an answer",
        "other": "unclassified failure",
    }
    return f"{words[kind]}: {detail}"


def run_checks(
    upload: storage.UploadClient,
    serve: storage.ServeClient,
    ck: Checks,
    *,
    key: str,
    body: bytes,
    http: HttpFn = http_request,
) -> None:
    """The assertions. Cleanup is NOT here — see verify(); this function may
    raise, and the object must go regardless."""

    # --- 1. The upload credential writes quarantine, through a presigned PUT
    print("\n-- upload credential: presigned PUT into quarantine --")
    presigned = storage.presign_upload(
        upload, key=key, content_length=len(body), content_type=TEST_CONTENT_TYPE
    )
    uploaded = False
    try:
        status = http(presigned.method, presigned.url, presigned.headers, body)
    except Exception as exc:  # noqa: BLE001 - classified, never re-raised here
        kind, detail = classify(exc)
        ck.check(False, "upload credential can PUT into quarantine (presigned)", _fail_detail(kind, detail))
    else:
        uploaded = ck.check(
            status in (200, 201),
            "upload credential can PUT into quarantine (presigned)",
            f"HTTP {status}",
        )

    # The size is signed, not trusted (§6.6): a body of another length must
    # fail the signature at the store. Anything but a rejection is a finding.
    if uploaded:
        try:
            status = http(
                presigned.method,
                presigned.url,
                {"Content-Type": TEST_CONTENT_TYPE},  # Content-Length from the (longer) body
                body + b"\x00",
            )
        except Exception as exc:  # noqa: BLE001
            kind, detail = classify(exc)
            ck.check(
                False,
                "a body whose length differs from the signed Content-Length is rejected",
                _fail_detail(kind, detail),
            )
        else:
            ck.check(
                400 <= status < 500,
                "a body whose length differs from the signed Content-Length is rejected",
                f"HTTP {status} - the store ACCEPTED a mismatched body; the signed size is not enforced"
                if status < 400
                else f"HTTP {status}",
            )
    else:
        ck.check(
            False,
            "a body whose length differs from the signed Content-Length is rejected",
            "not attempted: the PUT above failed",
        )

    # --- 2. The upload credential CAN read quarantine (positive; §3's bound)
    print("\n-- upload credential: reads quarantine (R2 has no write-only level) --")
    if uploaded:
        try:
            read_back = storage.read_quarantine_object(upload, key=key)
        except Exception as exc:  # noqa: BLE001
            kind, detail = classify(exc)
            ck.check(False, "upload credential can read quarantine", _fail_detail(kind, detail))
        else:
            ck.check(
                read_back == body,
                "upload credential can read quarantine, and reads back exactly what it wrote",
                f"read {len(read_back)} bytes, wrote {len(body)}",
            )
    else:
        ck.check(False, "upload credential can read quarantine", "not attempted: the PUT above failed")

    # --- 3. THE GUARANTEE: the serve credential is refused on quarantine
    print("\n-- serve credential: DENIED on quarantine (record section 3 - the reason this script exists) --")
    label = "serve credential is REFUSED reading quarantine"
    if not uploaded:
        # A refusal on an object that was never written proves nothing about
        # the object that matters; a wrong bucket name would look identical.
        ck.check(False, label, "not meaningful: the test object was never written (see the PUT above)")
    else:
        try:
            serve.raw.get_object(Bucket=upload.bucket, Key=key)
        except Exception as exc:  # noqa: BLE001
            kind, detail = classify(exc)
            if kind == "refused":
                ck.check(True, f"{label} ({detail})")
            else:
                ck.check(False, label, _fail_detail(kind, detail))
        else:
            ck.check(
                False,
                label,
                "the serve credential READ the quarantine object. Section 3's guarantee does "
                "not hold on the live buckets. This is a finding about infrastructure, not "
                "the script - report it and stop.",
            )

    # --- 4. The other two edges of the split (record §11.1)
    print("\n-- the other edges of the split (record section 11.1) --")
    # A not-found here is as damning as a success: the store looked for the
    # key, which it only does for a credential it let in.
    label = "upload credential is refused on published (quarantine-only scope)"
    admitted = "the upload credential was let into published - wider than section 11.1 records"
    try:
        upload.raw.get_object(Bucket=serve.bucket, Key=key)
    except Exception as exc:  # noqa: BLE001
        kind, detail = classify(exc)
        if kind == "refused":
            ck.check(True, f"{label} ({detail})")
        elif kind == "not_found":
            ck.check(False, label, f"{admitted} ({detail})")
        else:
            ck.check(False, label, _fail_detail(kind, detail))
    else:
        ck.check(False, label, admitted)

    label = "serve credential is refused WRITING to published (read-only scope)"
    wrote_published = False
    try:
        serve.raw.put_object(Bucket=serve.bucket, Key=key, Body=body, ContentType=TEST_CONTENT_TYPE)
    except Exception as exc:  # noqa: BLE001
        kind, detail = classify(exc)
        if kind == "refused":
            ck.check(True, f"{label} ({detail})")
        else:
            ck.check(False, label, _fail_detail(kind, detail))
    else:
        wrote_published = True
        ck.check(False, label, "the serve credential WROTE to published - it is meant to be read-only")
    if wrote_published:
        # Undo it with the credential that could do it, and say so either way.
        try:
            serve.raw.delete_object(Bucket=serve.bucket, Key=key)
        except Exception as exc:  # noqa: BLE001
            kind, detail = classify(exc)
            ck.check(
                False,
                "the stray published test object was deleted again",
                f"{_fail_detail(kind, detail)} - remove {key!r} from the published bucket by hand",
            )
        else:
            ck.info("stray published test object", "deleted again with the serve credential")

    # --- 5. The serve credential can read published
    print("\n-- serve credential: reads published --")
    label = "serve credential can read published (list)"
    try:
        serve.raw.list_objects_v2(Bucket=serve.bucket, MaxKeys=1)
    except Exception as exc:  # noqa: BLE001
        kind, detail = classify(exc)
        ck.check(False, label, _fail_detail(kind, detail))
    else:
        ck.check(True, label)

    # Through the serving path itself: a presigned GET minted by the serve
    # client. The published bucket holds nothing yet, so the honest outcomes
    # are 200 (something is there) and 404 (authorised, absent); a 403 means
    # the serving path is refused, whatever the list above said.
    label = "a serve-presigned GET against published is not refused"
    try:
        presigned_read = storage.presign_read(serve, key=key)
        status = http(presigned_read.method, presigned_read.url, {}, None)
    except Exception as exc:  # noqa: BLE001
        kind, detail = classify(exc)
        ck.check(False, label, _fail_detail(kind, detail))
    else:
        ck.check(
            status in (200, 404),
            f"{label} (HTTP {status}{' - authorised, key absent' if status == 404 else ''})"
            if status in (200, 404)
            else label,
            f"HTTP {status}",
        )


def cleanup(upload: storage.UploadClient, ck: Checks, *, key: str) -> None:
    """Delete the test object with the upload credential and confirm it is
    gone. Runs in verify()'s `finally`, so a failure mid-run leaves nothing."""
    print("\n-- cleanup: the test object leaves quarantine --")
    label = "test object deleted with the upload credential"
    try:
        storage.delete_quarantine_object(upload, key=key)
    except Exception as exc:  # noqa: BLE001
        kind, detail = classify(exc)
        ck.check(
            False,
            label,
            f"{_fail_detail(kind, detail)} - remove {key!r} from the quarantine bucket by hand; "
            "the 24-hour lifecycle rule removes it regardless",
        )
        return
    ck.check(True, label)
    try:
        remaining = storage.head_quarantine_object(upload, key=key)
    except Exception as exc:  # noqa: BLE001
        kind, detail = classify(exc)
        ck.check(False, "test object confirmed gone", _fail_detail(kind, detail))
    else:
        ck.check(remaining is None, "test object confirmed gone", "the object is still there")


def verify(
    upload: storage.UploadClient,
    serve: storage.ServeClient,
    ck: Checks,
    *,
    key: Optional[str] = None,
    http: HttpFn = http_request,
) -> None:
    """Run every check, then clean up whatever happened."""
    key = key or f"{TEST_KEY_PREFIX}{uuid.uuid4()}.bin"
    # Generated bytes with the key inside them - never a real file, and the
    # read-back in check 2 compares against exactly this.
    body = (f"covey-keep verify_r2_credentials test object {key} ".encode() + os.urandom(512))
    ck.info("test object key", key)
    try:
        run_checks(upload, serve, ck, key=key, body=body, http=http)
    finally:
        cleanup(upload, ck, key=key)


def settings_source() -> str:
    """Where the R2 values came from - the process environment (Render, or an
    exported shell) or backend/.env. Real env vars outrank the file."""
    if any(name.upper() == "R2_UPLOAD_ACCESS_KEY_ID" for name in os.environ):
        return "process environment"
    if (BACKEND_DIR / ".env").exists():
        return "backend/.env"
    return "unknown (Settings loaded, but neither the environment nor backend/.env carries R2_*)"


def main() -> int:
    # ASCII-only output, as verify_schema.py: a Windows console under cp1252
    # must not fail the verifier for cosmetic reasons.
    print("covey-keep R2 credential-split verifier")
    print(f"  settings from: {settings_source()}")
    print(f"  quarantine bucket: {settings.r2_bucket_quarantine}")
    print(f"  published bucket:  {settings.r2_bucket_published}")
    # Neither the endpoint (it carries the account id) nor either key id is printed.

    upload = storage.upload_client(settings)
    serve = storage.serve_client(settings)
    ck = Checks()
    verify(upload, serve, ck)

    print(f"\n{ck.passed} passed, {ck.failed} failed")
    return 1 if ck.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
