"""CK-36 — app/services/processing.py: decode, orient, strip, and render the
three layers.

THE TEST THAT MATTERS MOST IN THE ARC is the first one below, and it has a
real subject: `tests/fixtures/media/gps-oriented.jpg` is a genuine JPEG
carrying a genuine EXIF GPS IFD (the Bean, Chicago — never a home) and an
orientation tag, generated by `make_fixtures.py` beside it so its
provenance is on the record. It goes through the processor, and every one
of the three outputs is inspected two ways — Pillow's own EXIF reader, and
a scan of the raw bytes for an EXIF container — for any trace of what went
in. The EXIF promise has been stated in five decision records and executed
by nothing until this phase; asserting it against a mock would prove
nothing, so nothing here is mocked. No database, no network: this module
is pure functions over bytes.

Pinned:
- GPS (and every other EXIF field, and the ICC profile) is absent from all
  three layers of a real JPEG, a real PNG and a real HEIC that each carry
  it — and the fixtures are first shown to carry it, so a regenerated
  fixture without GPS cannot make the test pass vacuously;
- orientation is applied BEFORE stripping: the stored image's red top-left
  quadrant ends up top-RIGHT after a rotate-90-CW tag, in every layer;
- the three layers, their formats, content types, storage classes and
  long-edge targets; the thumbnail under ~30 KB; never upscaled — a small
  original yields three small renditions;
- the real format comes from the bytes: GIF, BMP and TIFF are refused as
  unsupported, a renamed .mov and random bytes as undecodable, a truncated
  JPEG as undecodable — every one Undecodable (permanent), reason in
  operator terms;
- the ~50 megapixel guard refuses from the header before any pixel is
  decoded (a 20 KB PNG of 50.4 megapixels), passes exactly 50, and also
  refuses what Pillow itself would refuse (twice the limit);
- transparency is flattened over white; an embedded ICC profile is
  converted in pixel space and not embedded; a garbage profile is ignored.
"""

import io
from pathlib import Path

import pytest
from PIL import ExifTags, Image, ImageCms

from app.models import MediaLayer
from app.services import processing
from app.services.processing import (
    ARCHIVAL_LONG_EDGE,
    DECODABLE_FORMATS,
    MAX_PIXELS,
    STORAGE_CLASS_INFREQUENT_ACCESS,
    STORAGE_CLASS_STANDARD,
    THUMBNAIL_LONG_EDGE,
    THUMBNAIL_TARGET_BYTES,
    WEB_LONG_EDGE,
    Undecodable,
    render_layers,
)

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "media"

RED = (255, 0, 0)
BLUE = (0, 0, 255)


def _fixture(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


def _exif(data: bytes) -> tuple[dict, dict]:
    """(every EXIF tag, the GPS IFD) as Pillow reads them from the bytes."""
    exif = Image.open(io.BytesIO(data)).getexif()
    return dict(exif), dict(exif.get_ifd(ExifTags.IFD.GPSInfo))


def _has_exif_container(data: bytes) -> bool:
    """A raw-bytes scan, independent of Pillow's reader: a JPEG APP1 EXIF
    segment, a WebP EXIF chunk, or a PNG eXIf chunk."""
    return b"Exif\x00\x00" in data or b"EXIF" in data or b"eXIf" in data


def _has_icc(data: bytes) -> bool:
    return b"ICC_PROFILE" in data or b"ICCP" in data or b"iCCP" in data


def _near(pixel, colour, tolerance=12) -> bool:
    return all(abs(a - b) <= tolerance for a, b in zip(pixel, colour))


def _encoded(image: Image.Image, fmt: str, **options) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, fmt, **options)
    return buffer.getvalue()


# --- the test that matters most --------------------------------------------------


@pytest.mark.parametrize("name", ["gps-oriented.jpg", "gps.png", "gps.heic"])
def test_gps_and_every_other_byte_of_metadata_is_absent_from_all_three_layers(name):
    data = _fixture(name)
    # The subject really carries GPS — otherwise the assertions below would
    # pass over nothing (the CK-20/21/34 lesson: a green run over an empty
    # subject is not evidence).
    tags, gps = _exif(data)
    assert gps[ExifTags.GPS.GPSLatitude] == (41.0, 52.0, 58.0)
    assert gps[ExifTags.GPS.GPSLongitudeRef] == "W"
    assert tags[ExifTags.Base.Make] == "CoveyKeep fixture"

    layers = render_layers(data)
    assert [r.layer for r in layers] == [MediaLayer.ARCHIVAL, MediaLayer.WEB, MediaLayer.THUMBNAIL]
    for rendition in layers:
        out_tags, out_gps = _exif(rendition.data)
        assert out_gps == {}, rendition.layer
        assert out_tags == {}, rendition.layer
        assert not _has_exif_container(rendition.data), rendition.layer
        assert not _has_icc(rendition.data), rendition.layer
        assert Image.open(io.BytesIO(rendition.data)).info.get("exif") is None


def test_orientation_is_applied_before_the_tag_is_stripped():
    """gps-oriented.jpg is stored 96x64 with its top-left quadrant red and
    carries orientation 6 (rotate 90° clockwise to display). Upright, it is
    64x96 with the red quadrant top-RIGHT. Stripping the tag without
    applying it would leave every layer 96x64 with red top-left — sideways
    on every screen, and looking like a UI bug."""
    data = _fixture("gps-oriented.jpg")
    stored = Image.open(io.BytesIO(data))
    assert stored.size == (96, 64)
    assert _near(stored.getpixel((0, 0)), RED)
    assert _exif(data)[0][ExifTags.Base.Orientation] == 6

    for rendition in render_layers(data):
        image = Image.open(io.BytesIO(rendition.data))
        assert image.size == (64, 96), rendition.layer
        assert (rendition.width, rendition.height) == (64, 96)
        assert _near(image.getpixel((image.width - 1, 0)), RED), rendition.layer
        assert _near(image.getpixel((0, 0)), BLUE), rendition.layer
        assert _near(image.getpixel((0, image.height - 1)), BLUE), rendition.layer
        # And no orientation tag survives to be applied a second time by a
        # viewer — which would rotate the upright image sideways again.
        assert ExifTags.Base.Orientation not in _exif(rendition.data)[0]


def test_an_unoriented_subject_keeps_its_layout():
    for name in ("gps.png", "gps.heic"):
        for rendition in render_layers(_fixture(name)):
            image = Image.open(io.BytesIO(rendition.data))
            assert image.size == (96, 64), (name, rendition.layer)
            assert _near(image.getpixel((0, 0)), RED), (name, rendition.layer)
            assert _near(image.getpixel((image.width - 1, 0)), BLUE), (name, rendition.layer)


# --- the three layers -----------------------------------------------------------


def _photo(width: int, height: int) -> bytes:
    """Photograph-like content (noise) so encoded sizes are realistic; a flat
    colour compresses to nothing and would make the thumbnail bound vacuous."""
    return _encoded(Image.effect_noise((width, height), 64).convert("RGB"), "JPEG", quality=92)


def test_the_three_layers_their_formats_classes_and_targets():
    archival, web, thumbnail = render_layers(_photo(6000, 4000))

    assert (archival.layer, archival.content_type, archival.storage_class) == (
        MediaLayer.ARCHIVAL,
        "image/jpeg",
        STORAGE_CLASS_INFREQUENT_ACCESS,
    )
    assert (web.layer, web.content_type, web.storage_class) == (
        MediaLayer.WEB,
        "image/webp",
        STORAGE_CLASS_STANDARD,
    )
    assert (thumbnail.layer, thumbnail.content_type, thumbnail.storage_class) == (
        MediaLayer.THUMBNAIL,
        "image/webp",
        STORAGE_CLASS_STANDARD,
    )
    assert Image.open(io.BytesIO(archival.data)).format == "JPEG"
    assert Image.open(io.BytesIO(web.data)).format == "WEBP"
    assert Image.open(io.BytesIO(thumbnail.data)).format == "WEBP"

    # Long-edge targets (media-layers record §1), aspect preserved.
    assert (archival.width, archival.height) == (ARCHIVAL_LONG_EDGE, 2667)
    assert (web.width, web.height) == (WEB_LONG_EDGE, 1707)
    assert (thumbnail.width, thumbnail.height) == (THUMBNAIL_LONG_EDGE, 267)
    for rendition in (archival, web, thumbnail):
        assert Image.open(io.BytesIO(rendition.data)).size == (rendition.width, rendition.height)
        assert rendition.size_bytes == len(rendition.data) > 0
    assert thumbnail.size_bytes <= THUMBNAIL_TARGET_BYTES
    # The record's numbers, so nobody re-imports the wrong ones.
    assert (ARCHIVAL_LONG_EDGE, WEB_LONG_EDGE, THUMBNAIL_TARGET_BYTES) == (4000, 2560, 30_000)
    assert (STORAGE_CLASS_INFREQUENT_ACCESS, STORAGE_CLASS_STANDARD) == ("STANDARD_IA", "STANDARD")


def test_a_portrait_original_fits_its_long_edge():
    archival, web, thumbnail = render_layers(_photo(3000, 4500))
    assert (archival.width, archival.height) == (2667, ARCHIVAL_LONG_EDGE)
    assert (web.width, web.height) == (1707, WEB_LONG_EDGE)
    assert (thumbnail.width, thumbnail.height) == (267, THUMBNAIL_LONG_EDGE)


def test_a_small_original_is_never_upscaled_and_still_yields_three_layers():
    layers = render_layers(_photo(320, 240))
    assert len(layers) == 3
    for rendition in layers:
        assert (rendition.width, rendition.height) == (320, 240), rendition.layer
    # And a mid-sized one is reduced only where it exceeds a target.
    archival, web, thumbnail = render_layers(_photo(3000, 2000))
    assert (archival.width, archival.height) == (3000, 2000)
    assert (web.width, web.height) == (WEB_LONG_EDGE, 1707)
    assert (thumbnail.width, thumbnail.height) == (THUMBNAIL_LONG_EDGE, 267)


# --- the real format, from the bytes ------------------------------------------------


@pytest.mark.parametrize("fmt", ["GIF", "BMP", "TIFF"])
def test_a_decodable_but_unsupported_format_is_refused_permanently(fmt):
    data = _encoded(Image.new("RGB", (64, 48), "green"), fmt)
    with pytest.raises(Undecodable) as excinfo:
        render_layers(data)
    assert excinfo.value.reason == f"{fmt} is not a supported photograph format"
    assert fmt not in DECODABLE_FORMATS


def test_the_decodable_formats_are_exactly_the_allowlists_real_counterpart():
    # image/jpeg, png, webp, heic, heif at the intent endpoint; pillow-heif
    # reports HEIC and HEIF alike as HEIF.
    assert DECODABLE_FORMATS == {"JPEG", "PNG", "WEBP", "HEIF"}
    for fmt in ("JPEG", "PNG", "WEBP"):
        assert len(render_layers(_encoded(Image.new("RGB", (64, 48), "green"), fmt))) == 3


@pytest.mark.parametrize(
    "data, reason",
    [
        # The Live Photo's MOV half, renamed: a QuickTime `ftyp` box.
        (b"\x00\x00\x00\x14ftypqt  \x00\x00\x00\x00qt  " + bytes(300), "UnidentifiedImageError"),
        (b"this is not a photograph", "UnidentifiedImageError"),
        (b"", "UnidentifiedImageError"),
    ],
)
def test_bytes_that_are_not_an_image_are_refused_permanently(data, reason):
    with pytest.raises(Undecodable) as excinfo:
        render_layers(data)
    assert excinfo.value.reason == f"not a decodable image ({reason})"


def test_a_truncated_photograph_is_refused_permanently():
    data = _photo(3000, 2000)[:20_000]
    with pytest.raises(Undecodable) as excinfo:
        render_layers(data)
    assert excinfo.value.reason.startswith("not a decodable image (")
    # Operator terms: an exception class, never the bytes.
    assert "\\x" not in excinfo.value.reason


# --- the pixel guard ----------------------------------------------------------------


def _tiny_png_of(width: int, height: int) -> bytes:
    # A 1-bit PNG: a huge pixel count in a small file — the decompression
    # bomb shape record §6.6 names (bytes bound nothing; pixels do).
    return _encoded(Image.new("1", (width, height), 1), "PNG")


def test_the_pixel_guard_refuses_from_the_header_before_any_pixel_is_decoded():
    assert MAX_PIXELS == 50_000_000
    bomb = _tiny_png_of(7100, 7100)  # 50.41 MP
    assert len(bomb) < 50_000  # the byte cap alone would wave it through
    with pytest.raises(Undecodable) as excinfo:
        render_layers(bomb)
    assert excinfo.value.reason == "larger than the 50 megapixel limit"
    # Pillow's own protection, mirrored to the same number, is the backstop
    # for anything past twice it.
    assert Image.MAX_IMAGE_PIXELS == MAX_PIXELS
    with pytest.raises(Undecodable) as excinfo:
        render_layers(_tiny_png_of(10_100, 10_100))  # 102 MP
    assert excinfo.value.reason == "larger than the 50 megapixel limit"


def test_exactly_the_limit_passes():
    archival, web, thumbnail = render_layers(_tiny_png_of(5000, 10_000))  # 50.0 MP
    assert (archival.width, archival.height) == (2000, ARCHIVAL_LONG_EDGE)
    assert (web.width, web.height) == (1280, WEB_LONG_EDGE)
    assert (thumbnail.width, thumbnail.height) == (200, THUMBNAIL_LONG_EDGE)


# --- pixels, not metadata: transparency and colour ------------------------------------


def test_transparency_is_flattened_over_white():
    data = _encoded(Image.new("RGBA", (50, 40), (255, 0, 0, 0)), "PNG")
    for rendition in render_layers(data):
        assert _near(Image.open(io.BytesIO(rendition.data)).getpixel((0, 0)), (255, 255, 255))


def test_an_embedded_icc_profile_is_converted_in_pixel_space_and_never_embedded():
    icc = ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes()
    data = _encoded(Image.new("RGB", (40, 30), (200, 100, 50)), "JPEG", quality=95, icc_profile=icc)
    assert _has_icc(data)
    for rendition in render_layers(data):
        assert not _has_icc(rendition.data), rendition.layer
        assert Image.open(io.BytesIO(rendition.data)).info.get("icc_profile") is None
        # sRGB -> sRGB is the identity: the colour survives the profile's removal.
        assert _near(Image.open(io.BytesIO(rendition.data)).getpixel((0, 0)), (200, 100, 50))


def test_a_profile_that_will_not_parse_is_ignored_rather_than_dead_lettering():
    data = _encoded(Image.new("RGB", (40, 30), (200, 100, 50)), "JPEG", quality=95, icc_profile=b"not a profile")
    layers = render_layers(data)
    assert len(layers) == 3
    assert _near(Image.open(io.BytesIO(layers[0].data)).getpixel((0, 0)), (200, 100, 50))


def test_the_module_logs_nothing_and_names_no_row():
    # Pure functions over bytes: no logger, no database, no storage import.
    assert "logging" not in vars(processing)
    assert "AsyncSession" not in vars(processing)
    assert not any(name.startswith("storage") for name in vars(processing))
